version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # <-- Change this from 18 to 20
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'
